<?php

use Drupal\Core\Database\Database;

/**
 * Implements hook_uninstall().
 *
 * Cleans up config entities installed by this module.
 */
function custom_migrate_article_uninstall() {
  \Drupal::database()->query("DELETE FROM {config} WHERE name LIKE '%migrate_plus.migration.custom_migrate_article%'");
  \Drupal::database()->query("DELETE FROM {config} WHERE name LIKE '%migrate_plus.migration.custom_migrate_files%'");
 
  drupal_flush_all_caches();
}
